export const CHECK_STORE = "CHECK_STORE";
export const CHECK_STORE_REQ = "CHECK_STORE_REQ";

export const SET_RESPONSIVE = "SET_RESPONSIVE";
export const SET_RESPONSIVE_REQ = "SET_RESPONSIVE_REQ";

export const IS_OPEN_MODAL = "IS_OPEN_MODAL";
export const IS_OPEN_MODAL_REQ = "IS_OPEN_MODAL_REQ";


//api Call data
export const CALL_ALL_DATA_API = "CALL_ALL_DATA_API";
export const CALL_ALL_DATA_API_REQ = "CALL_ALL_DATA_API_REQ";

export const CREATE_DATA_API = "CREATE_DATA_API";
export const CREATE_DATA_API_REQ = "CREATE_DATA_API_REQ";

export const UPDATE_DATA_API = "UPDATE_DATA_API";
export const UPDATE_DATA_API_REQ = "UPDATE_DATA_API_REQ";