export const CHECK_STORE = "CHECK_STORE";
export const CHECK_STORE_REQ = "CHECK_STORE_REQ";

export const SET_RESPONSIVE = "SET_RESPONSIVE";
export const SET_RESPONSIVE_REQ = "SET_RESPONSIVE_REQ";

export const IS_OPEN_MODAL = "IS_OPEN_MODAL";
export const IS_OPEN_MODAL_REQ = "IS_OPEN_MODAL_REQ";