export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const ADD_ITEM_TO_CART_REQ = "ADD_ITEM_TO_CART_REQ";

export const CALL_ITEM_CART = "CALL_ITEM_CART";
export const CALL_ITEM_CART_REQ = "CALL_ITEM_CART_REQ";

export const DELETE_ITEM_IN_CART = "DELETE_ITEM_IN_CART";
export const DELETE_ITEM_IN_CART_REQ = "DELETE_ITEM_IN_CART_REQ";

export const CHANGE_ITEM_IN_CART = "CHANGE_ITEM_IN_CART";
export const CHANGE_ITEM_IN_CART_REQ = "CHANGE_ITEM_IN_CART_REQ";
