export const CATEGORY_CALL_ALL_DATA_API = "CATEGORY_CALL_ALL_DATA_API";
export const CATEGORY_CALL_ALL_DATA_API_REQ = "CATEGORY_CALL_ALL_DATA_API_REQ";

export const CATEGORY_CREATE_DATA_API = "CATEGORY_CREATE_DATA_API";
export const CATEGORY_CREATE_DATA_API_REQ = "CATEGORY_CREATE_DATA_API_REQ";

export const CATEGORY_UPDATE_DATA_API = "CATEGORY_UPDATE_DATA_API";
export const CATEGORY_UPDATE_DATA_API_REQ = "CATEGORY_UPDATE_DATA_API_REQ";

export const CATEGORY_DELETE_DATA_API = "CATEGORY_DELETE_DATA_API";
export const CATEGORY_DELETE_DATA_API_REQ = "CATEGORY_DELETE_DATA_API_REQ";