export const MAIN_CATEGORY_CALL_ALL_DATA_API = "MAIN_CATEGORY_CALL_ALL_DATA_API";
export const MAIN_CATEGORY_CALL_ALL_DATA_API_REQ = "MAIN_CATEGORY_CALL_ALL_DATA_API_REQ";

export const MAIN_CATEGORY_CREATE_DATA_API = "MAIN_CATEGORY_CREATE_DATA_API";
export const MAIN_CATEGORY_CREATE_DATA_API_REQ = "MAIN_CATEGORY_CREATE_DATA_API_REQ";

export const MAIN_CATEGORY_UPDATE_DATA_API = "MAIN_CATEGORY_UPDATE_DATA_API";
export const MAIN_CATEGORY_UPDATE_DATA_API_REQ = "MAIN_CATEGORY_UPDATE_DATA_API_REQ";

export const MAIN_CATEGORY_DELETE_DATA_API = "MAIN_CATEGORY_DELETE_DATA_API";
export const MAIN_CATEGORY_DELETE_DATA_API_REQ = "MAIN_CATEGORY_DELETE_DATA_API_REQ";