export const ORDER_CALL_BY_ID_DATA_API = "ORDER_CALL_BY_ID_DATA_API";
export const ORDER_CALL_BY_ID_DATA_API_REQ = "ORDER_CALL_BY_ID_DATA_API_REQ";

export const CHANGE_STATUS_ORDER = "CHANGE_STATUS_ORDER";
export const CHANGE_STATUS_ORDER_REQ = "CHANGE_STATUS_ORDER_REQ";

