export const CALL_PRODUCT_HISTORY_DATA_API = "CALL_PRODUCT_HISTORY_DATA_API";
export const CALL_PRODUCT_HISTORY_DATA_API_REQ = "CALL_PRODUCT_HISTORY_DATA_API_REQ";

export const CHANGE_PRODUCT_HISTORY_DATA_API = "CHANGE_PRODUCT_HISTORY_DATA_API";
export const CHANGE_PRODUCT_HISTORY_DATA_API_REQ = "CHANGE_PRODUCT_HISTORY_DATA_API_REQ";

export const CLEAR_PRODUCT_HISTORY_DATA_API = "CLEAR_PRODUCT_HISTORY_DATA_API";
export const CLEAR_PRODUCT_HISTORY_DATA_API_REQ = "CLEAR_PRODUCT_HISTORY_DATA_API_REQ";