export const PRODUCT_CALL_ALL_DATA_API = "PRODUCT_CALL_ALL_DATA_API";
export const PRODUCT_CALL_ALL_DATA_API_REQ = "PRODUCT_CALL_ALL_DATA_API_REQ";

export const PRODUCT_CREATE_DATA_API = "PRODUCT_CREATE_DATA_API";
export const PRODUCT_CREATE_DATA_API_REQ = "PRODUCT_CREATE_DATA_API_REQ";

export const PRODUCT_UPDATE_DATA_API = "PRODUCT_UPDATE_DATA_API";
export const PRODUCT_UPDATE_DATA_API_REQ = "PRODUCT_UPDATE_DATA_API_REQ";

export const PRODUCT_DELETE_DATA_API = "PRODUCT_DELETE_DATA_API";
export const PRODUCT_DELETE_DATA_API_REQ = "PRODUCT_DELETE_DATA_API_REQ";