export const PRODUCT_CALL_FILTER_DATA_API = "PRODUCT_CALL_FILTER_DATA_API";
export const PRODUCT_CALL_FILTER_DATA_API_REQ = "PRODUCT_CALL_FILTER_DATA_API_REQ";

export const PRODUCT_CREATE_HISTORY_DATA_API = "PRODUCT_CREATE_HISTORY_DATA_API";
export const PRODUCT_CREATE_HISTORY_DATA_API_REQ = "PRODUCT_CREATE_HISTORY_DATA_API_REQ";