export const SERVICE_GET_ORDER = "SERVICE_GET_ORDER";
export const SERVICE_GET_ORDER_REQ = "SERVICE_GET_ORDER_REQ";

export const SERVICE_CHANGE_STATUS_ORDER = "SERVICE_CHANGE_STATUS_ORDER";
export const SERVICE_CHANGE_STATUS_ORDER_REQ = "SERVICE_CHANGE_STATUS_ORDER_REQ";