export const STORE_CALL_ALL_DATA_API = "STORE_CALL_ALL_DATA_API";
export const STORE_CALL_ALL_DATA_API_REQ = "STORE_CALL_ALL_DATA_API_REQ";

export const STORE_CREATE_DATA_API = "STORE_CREATE_DATA_API";
export const STORE_CREATE_DATA_API_REQ = "STORE_CREATE_DATA_API_REQ";

export const STORE_UPDATE_DATA_API = "STORE_UPDATE_DATA_API";
export const STORE_UPDATE_DATA_API_REQ = "STORE_UPDATE_DATA_API_REQ";

export const STORE_DELETE_DATA_API = "STORE_DELETE_DATA_API";
export const STORE_DELETE_DATA_API_REQ = "STORE_DELETE_DATA_API_REQ";