export const GET_STORE_ORDER = "GET_STORE_ORDER";
export const GET_STORE_ORDER_REQ = "GET_STORE_ORDER_REQ";

export const DEL_STORE_ORDER = "DEL_STORE_ORDER";
export const DEL_STORE_ORDER_REQ = "DEL_STORE_ORDER_REQ";

export const UPDATE_STATUS_STORE_ORDER = "UPDATE_STATUS_STORE_ORDER";
export const UPDATE_STATUS_STORE_ORDER_REQ = "UPDATE_STATUS_STORE_ORDER_REQ";

export const CLEAR_STORE_ORDER = "CLEAR_STORE_ORDER";
export const CLEAR_STORE_ORDER_REQ = "CLEAR_STORE_ORDER_REQ";

export const ADD_TO_CART_STORE_ORDER = "ADD_TO_CART_STORE_ORDER";
export const ADD_TO_CART_STORE_ORDER_REQ = "ADD_TO_CART_STORE_ORDER_REQ";