export const TYPE_CALL_ALL_DATA_API = "TYPE_CALL_ALL_DATA_API";
export const TYPE_CALL_ALL_DATA_API_REQ = "TYPE_CALL_ALL_DATA_API_REQ";

export const TYPE_CREATE_DATA_API = "TYPE_CREATE_DATA_API";
export const TYPE_CREATE_DATA_API_REQ = "TYPE_CREATE_DATA_API_REQ";

export const TYPE_UPDATE_DATA_API = "TYPE_UPDATE_DATA_API";
export const TYPE_UPDATE_DATA_API_REQ = "TYPE_UPDATE_DATA_API_REQ";

export const TYPE_DELETE_DATA_API = "TYPE_DELETE_DATA_API";
export const TYPE_DELETE_DATA_API_REQ = "TYPE_DELETE_DATA_API_REQ";